import React from 'react';
import { Trophy } from 'lucide-react';
import type { TraitDescription } from '../../types';

interface ExportTemplateProps {
  result: TraitDescription;
  date: string;
}

export function ExportTemplate({ result, date }: ExportTemplateProps) {
  return (
    <div className="bg-white text-[#1C1A31] p-8 rounded-lg max-w-3xl mx-auto">
      {/* Header */}
      <div className="text-center border-b border-gray-200 pb-6 mb-6">
        <Trophy className="w-12 h-12 text-[#9263D9] mx-auto mb-4" />
        <h1 className="text-3xl font-bold mb-2">Communication Style Assessment</h1>
        <p className="text-gray-500">Assessment Date: {date}</p>
      </div>

      {/* Main Result */}
      <div className="mb-8 text-center">
        <h2 className="text-2xl font-bold text-[#9263D9] mb-2">
          Your Communication Style: {result.trait}
        </h2>
        <p className="text-gray-700">{result.description}</p>
      </div>

      {/* Details Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="space-y-3">
          <h3 className="font-semibold text-lg text-[#9263D9]">Key Indicators</h3>
          <ul className="space-y-2">
            {result.indicators.map((item, index) => (
              <li key={index} className="flex items-start">
                <span className="text-[#C0E021] mr-2">•</span>
                <span className="text-gray-700">{item}</span>
              </li>
            ))}
          </ul>
        </div>

        <div className="space-y-3">
          <h3 className="font-semibold text-lg text-[#9263D9]">Strengths</h3>
          <ul className="space-y-2">
            {result.strengths.map((item, index) => (
              <li key={index} className="flex items-start">
                <span className="text-[#C0E021] mr-2">•</span>
                <span className="text-gray-700">{item}</span>
              </li>
            ))}
          </ul>
        </div>

        <div className="space-y-3">
          <h3 className="font-semibold text-lg text-[#9263D9]">Growth Areas</h3>
          <ul className="space-y-2">
            {result.improvements.map((item, index) => (
              <li key={index} className="flex items-start">
                <span className="text-[#C0E021] mr-2">•</span>
                <span className="text-gray-700">{item}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Footer */}
      <div className="mt-8 pt-6 border-t border-gray-200 text-center text-gray-500">
        <p>Generated by Communication Style Assessment Tool</p>
      </div>
    </div>
  );
}